version = 1

[merge]
priority_merge_label = "automerge: first"
notify_on_conflict = false

[merge.message]
title = "pull_request_title" # default: "github_default"
body = "pull_request_body"   # default: "github_default"

[update]
ignored_usernames = ["renovate"]
