name: Publish Pull Requests

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    outputs:
      has-permissions: ${{ steps.checkPermissions.outputs.require-result }}
    steps:
      - name: Check permissions for approver
        id: checkPermissions
        uses: actions-cool/check-user-permission@v2
        with:
          require: "write"

  publish:
    needs: [check]
    if: >
      needs.check.outputs.has-permissions == 'true' || 
      github.event.pull_request.user.type == 'User' && 
      github.event.pull_request.user.site_admin == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build:packages

      - run: pnpx pkg-pr-new publish --compact './packages/*'
